import { notFound } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { getStoryById } from "@/lib/supabase-queries";
import { Database } from "@/lib/database.types";

type Story = Database["public"]["Tables"]["stories"]["Row"];
type Source = Database["public"]["Tables"]["sources"]["Row"];

interface StoryWithSources extends Story {
  sources: Source[];
}

interface StoryPageProps {
  params: Promise<{ id: string }>;
}

export default async function StoryPage({ params }: StoryPageProps) {
  const { id } = await params;
  const story = await getStoryById(id) as StoryWithSources | null;

  if (!story) {
    notFound();
  }

  const formattedDate = story.created_at
    ? new Date(story.created_at).toLocaleDateString("en-US", {
        weekday: "long",
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : null;

  return (
    <>
      {/* Main split layout: 50% image / 50% content */}
      <div className="flex flex-col md:flex-row min-h-screen md:min-h-[calc(100vh-80px)]">
        {/* Left: Image (50%) */}
        <div className="w-full md:w-1/2 bg-gray-100 flex flex-col">
          <div className="relative w-full min-h-[40vh] md:min-h-0 flex-1">
            {/* Floating Back button */}
            <Link
              href="/"
              className="absolute top-3 left-3 md:top-4 md:left-4 z-10 inline-flex items-center gap-1 bg-black/60 hover:bg-black/80 text-white text-xs md:text-sm font-medium px-3 py-1.5 md:px-4 md:py-2 rounded-full backdrop-blur-sm transition-colors"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-3 w-3 md:h-4 md:w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
              </svg>
              <span className="hidden xs:inline">Back</span>
            </Link>

            {story.image_url ? (
              <Image
                src={story.image_url}
                alt={story.title}
                fill
                className="object-cover"
                sizes="(max-width: 768px) 100vw, 50vw"
                priority
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center text-gray-400 text-lg">
                No image available
              </div>
            )}
          </div>

          {/* AI-generated note – below the image */}
          <p className="text-xs text-gray-400 italic text-center py-2 md:py-3">
            Image generated by AI agents
          </p>
        </div>

        {/* Right: Content (50%) */}
        <div className="w-full md:w-1/2 p-5 sm:p-6 md:p-10 lg:p-12 overflow-y-auto flex flex-col space-y-4 bg-white">
          <h1 className="text-xl sm:text-2xl md:text-3xl lg:text-4xl font-bold text-gray-900 leading-tight">
            {story.title}
          </h1>

          {formattedDate && (
            <p className="text-sm text-gray-500">{formattedDate}</p>
          )}

          <div className="text-gray-700 text-base sm:text-lg leading-relaxed">
            <p>{story.summary}</p>
          </div>

          {/* Why it matters */}
          <div className="bg-blue-50 border-l-4 border-blue-500 p-3 sm:p-4 rounded-r-md">
            <h3 className="font-semibold text-blue-800">Why it matters</h3>
            <p className="text-gray-700 text-sm sm:text-base">{story.why_it_matters}</p>
          </div>

          {/* Key points */}
          {story.key_points && story.key_points.length > 0 && (
            <div>
              <h3 className="text-base sm:text-lg font-semibold text-gray-900 mb-2">Key points</h3>
              <ul className="list-disc pl-5 sm:pl-6 space-y-1 text-gray-700 text-sm sm:text-base">
                {story.key_points.map((point: string, index: number) => (
                  <li key={index}>{point}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Sources */}
          {story.sources && story.sources.length > 0 && (
            <div className="border-t border-gray-200 pt-4 mt-2">
              <h3 className="text-base sm:text-lg font-semibold text-gray-900 mb-2">Sources</h3>
              <ul className="space-y-1 text-sm sm:text-base">
                {story.sources.map((source: Source) => (
                  <li key={source.id}>
                    <a
                      href={source.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-600 hover:underline break-all"
                    >
                      {source.publisher || source.url}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>
    </>
  );
}